#pragma once

#define ERR_SOCKETINITIALIZEFAILED -2
#define ERR_LISTENSOCKETCREATEFAIL -3
#define ERR_ADDRINFOFAILED -4
#define ERR_BINDFAIL -5
#define ERR_INVALIDLISTENSOCKET -6
#define ERR_LISTENFAILURE -7
#define ERR_INVALIDCLIENTSOCKET -8
#define ERR_SENDTOCLIENTFAILED -9
#define ERR_RECIEVEFROMCLIENTFAILED -10
#define ERR_SHUTDOWNSOCKETERROR -11

#define ERR_REQUESTSIZELESS -12
#define ERR_REQUESTSTRINGNULL -13
#define ERR_CANNOTIDENTIFYMETHOD -14
#define ERR_INVALID_REQUEST -15
#define ERR_NOT_FOUND_HTTP_VER -16

#define ERR_INVALID_PARAMETERS -17
