#pragma once

#define ERR_WSASTARTUPFAILED -2
#define ERR_GETSERVERADDRFAIL -3
#define ERR_SOCKETCREATIONFAIL -4
#define ERR_SERVERCONNECTIONFAIL -5
#define ERR_INVALIDSOCKET -6
#define ERR_SERVERSENDERROR -7
#define ERR_SERVERRECVERROR -8
